name: Build and test C

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  c_format_check:
    env:
      WORKSPACE: ${{ github.workspace }}/gsad
    name: Check C Source Code Formatting
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Check Source Format
        run: clang-format -i -style=file ${{ env.WORKSPACE }}/src/*.{c,h} && git diff --exit-code
