name: Build and test C

on:
  push:
    branches: [ master, stable, oldstable ]
  pull_request:
    branches: [ master, stable, oldstable ]


jobs:
  c-format-check:
    name: Check C Source Code Formatting
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Check Source Format
        run: |
          clang-format -i -style=file src/*.{c,h}
          git diff --exit-code
  build-gsad:
    name: Build gsad
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        container:
          - greenbone/gsad-gcc-build:stable
          - greenbone/gsad-clang-build:stable
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Configure and compile gsad
        run: |
          mkdir build
          rm -rf .git
          cd build/
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make install
